### ISSUE TITLE
Error: <LANG> not a valid tesseract language string

### ISSUE THREAD

**Issue by DEAN-Cherry** [mgmeyers/pdfannots2json#17]
OS : Windows 11 22H2
tesseract version: v5.2.0.20220712
pdfannots2json: latest

Problem: Using `pdfannots2json.exe` but got error says the parameter in `-l` invaild.

![图片](https://user-images.githubusercontent.com/76607677/205243210-e9993781-9793-48eb-92cd-2ae6dd0ec093.png)

ps. I have tried a pure `tesseract` command and everything works perfectly.

full version information:
![图片](https://user-images.githubusercontent.com/76607677/205243676-d3d49efd-3bf6-4573-88be-ac2c39b18f18.png)

**Comment by mgmeyers** [comment]
@DEAN-Cherry This should be fixed now in version `1.0.15`. Let me know if you still have issues

**Comment by gwd666** [comment]
this error can happen in case you have set the `TESSDATA_PREFIX` environment variable in a "too short" way, ie not up until ie including the `...\tessdata` folder;   
at least for me (on WIN11), because afaict the `ValidateLang` results will then be looking something like `tesserdata\eng`, which will evaluate to `false` for `found` ...  
just dropping this comment here in case someone else does the same stupid mistake ie stumbles across this
